### ISSUE TITLE
Password protected rars

### ISSUE THREAD

**Issue by ChrisJollyAU** [xbmc/vfs.rar#18]
Currently vfs.rar can not handle password protected rar files. Should support be added or not?

**Comment by notspiff** [comment]
Problem is crypto is one of the things which actually changed in later
years and rarlib is from ~ 2003. To have it work reliably you would have to
bump to something recent and my hacks do not easily rebase.

19. sep. 2017 9:29 p.m. skrev "Christopher Jolly" <notifications@github.com

**Comment by AlwinEsch** [comment]
Should be fixed on ​https://github.com/xbmc/vfs.rar/pull/50 and password support added back
