### ISSUE TITLE
Subtitles are not extracted when they are in a rar inside a rar

### ISSUE THREAD

**Issue by amazingdash** [xbmc/vfs.rar#34]
Hello, before v18, kodi properly handled subs inside rars inside rars:
```
INFO: ScanArchiveForAssociatedItems: found associated file rar://****%2fSubs%2fmovie.subs.rar/movie.idx
DEBUG: ScanArchiveForAssociatedItems: Scanning archive rar://****%2fSubs%2fmovie.subs.rar/movie.rar
DEBUG: Thread RarFileExtract start, auto delete: false
DEBUG: Thread RarFileExtract 140642999072512 terminating
INFO: ScanArchiveForAssociatedItems: found associated file rar://rar%3a%2f*****%252fmovie%252fSubs%252fmovie.subs.rar%2fmovie.rar/movie.sub
``` 
This does not work with this addon. This is a problem because subtitles are often in a weird format, they are in a RAR file that contains:
* an IDX file
* a RAR file that contains the SUB file

With the vfs addon, only the top level IDX file is extracted.

**Comment by Sopor** [comment]
For me it will work if i manually load the subs, but it will not auto-load and it doesn't matter if it is STORED or BEST compression.

I'm running Kodi 18.5 on Windows 10 x64 1903

**Comment by AlwinEsch** [comment]
The new version is released:
- 3.3.0-Matrix
- 2.3.0-Leia

During my tests it was OK, @amazingdash and @Sopor can you confirm?

**Comment by Sopor** [comment]
@AlwinEsch I did a test with 2.3.0 and it will still not auto-load the subtitles :(

But i don't know if it has something to do with the empty file name?

![image](https://user-images.githubusercontent.com/5789283/78726605-b4640180-7932-11ea-8b8f-6c10c92e507d.png)

**Comment by AlwinEsch** [comment]
Ah forget that is in Kodi Leia itself. Possible that related with this.
There was this about https://github.com/xbmc/xbmc/pull/17485 which then in Leia 18.7 fixed.

Has tested before with Kodi Matrix where it has worked by me with them.

**Comment by amazingdash** [comment]
@AlwinEsch It still doesn't autoload subtitles with 2.3.0. I have built Kodi 18.6 with the backport that you linked.

However, I can now browse for subtitles from the rar in rar and select them, I'm not sure this used to be possible. It's still very annoying because browse doesn't show the current folder.

Can you try with 18.6 (+ the patch you mentioned)? I doubt it will work for you either. If necessary, I can provide you with test files, let me know.

**Comment by AlwinEsch** [comment]
This part is now fixed within Leia and Matrix, after release of Kodi 18.8 is it then available for use.

- https://github.com/xbmc/xbmc/pull/18202
- https://github.com/xbmc/xbmc/pull/18201
