### ISSUE TITLE
RAR not working on external sources

### ISSUE THREAD

**Issue by Stargrove** [xbmc/vfs.rar#38]
Hi, 
I installed 18.1 with a ftp source which contains rar files. These files are not shown as rar nor as mkv or mp4. On local harddrives, it is working. This worked fine under 17.X an older, but now with moving rar support to add ons, it is no more possible to direct stream from a ftp source.
Maybe nobody has realized this or do I need another setting which I havent found?

Regards,
Arbi

**Comment by Stargrove** [comment]
I forgot to mention: I use Kodi 18.1 under Ubuntu 18.04, installed via Repo incl. vfs-rar, vfs-libarchive.

**Comment by notspiff** [comment]
debug log. you analysis is not correct.

**Comment by Stargrove** [comment]
You are righ, it works on some directories, some not.
I found also that the sftp plugin seems to disturb a little bit.

Sometimes I run into this issue which causes Kodi to run into a endless loop saying busy
INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)

Also the initial display of the rar file or its content takes a lot longer that 17.X which worked a little bit different as it seems,. the content was listed faster
Overall, because a working rar lib with ftp server is a must for me, I go back to 17.6. The implementation of ftp and rar is better for my needs.

**Comment by Stargrove** [comment]
After installing the 17.6 version, I saw in log file that Version 18.1 seems to go through all existing rar files. Version 17.6. only checks the first  rar file and the last rar file. On archives with a lot of packed files, it takes too long to go through all the file which results in an endless loop or showing nothing.

**Comment by notspiff** [comment]
use vfs.rar then instead of vfs.libarchive. vfs.rar still has all the hacks to avoid opening all archives, at the cost of a lot of bugs. vfs.libarchive does everything correctly, but on shitty ftp's...

**Comment by AlwinEsch** [comment]
@Stargrove how it works on latest versions (and vfs.libarchive disabled), still problem present on ftp?

**Comment by Stargrove** [comment]
@AlwinEsch thanks for asking, it works as expected

**Comment by AlwinEsch** [comment]
Thanks a lot!
