### ISSUE TITLE
Kodi crash on some rar file

### ISSUE THREAD

**Issue by taxigps** [xbmc/vfs.rar#39]
test file see attach
[Spider-Man.rar.zip](https://github.com/xbmc/vfs.rar/files/2966353/Spider-Man.rar.zip)

**Comment by notspiff** [comment]
i cannot reproduce any crash. it fails due to lack of wname handling though. you actually see a crash?

**Comment by taxigps** [comment]
yes, crash every time when call xbmcvfs.listdir with this rar file. test on windows 7/10.

**Comment by notspiff** [comment]
can you check if https://github.com/notspiff/vfs.rar/pull/new/fix_wnames takes care of it?

**Comment by taxigps** [comment]
still crash

**Comment by notspiff** [comment]
i cannot reproduce any crash on linux so i can't help you then :/

**Comment by Rechi** [comment]
@taxigps please give detailed steps on how to reproduce the crash.

**Comment by taxigps** [comment]
@Rechi The crash is arises on  windows 10 system. my test code here:
```
import os
from urllib import quote_plus as url_quote
import xbmcvfs

directory_from = 'D:/temp/Spider-Man.rar'
directory_to = 'D:/temp/'
path = url_quote(directory_from)
print('Archive file test')
(dirs, files) = xbmcvfs.listdir('rar://%s' % (path))
print('Dirs and files')
print(dirs)
print(files)
src = 'rar://%s' % (path) + '/' + files[0]
print(xbmcvfs.exists(src))
dest = os.path.join(directory_to,files[0])
print('Test copy from archive %s to %s' %(src, dest))
success = xbmcvfs.copy(src, dest)
print(success)
print('Copied file exists test from archive')
print(xbmcvfs.exists(dest))
```
and  just use File manage of Kodi to  browse Spider-Man.rar will crash Kodi.

@notspiff It seems that there is no plug-in vfs.rar for Linux system. how to use rar under linux?

**Comment by notspiff** [comment]
either you build it, or you install it from the kodi ppa.

possible way to do it:
1) build kodi somewhere, the folder is referred to as $BUILD_DIR
2) clone the add-on code somewhere
3) configure using cmake <root-of-add-on-code> -DCMAKE_PREFIX_PATH=$BUILD_DIR/build -DKODI_BUILD_DIR=$BUILD_DIR

this will build and install the add-on in the build tree. now just run kodi out of the build tree.

**Comment by Rechi** [comment]
@taxigps I've tested your code (on Windows 10), it doesn't crash. But it also doesn't do what's expected.
\
Applied #40 and it works.

**Comment by taxigps** [comment]
@notspiff thanks.
@Rechi so only crash with chinese version of windows? may be unicode string cause overflow somewhere. I'll try to look into the source code to find it when have time.

**Comment by taxigps** [comment]
may be the bug is here: https://github.com/xbmc/vfs.rar/blob/b66c6df9f1c4b683bf8e3563908fd204e273238c/lib/UnrarXLib/file.cpp#L107
https://github.com/xbmc/vfs.rar/blob/b66c6df9f1c4b683bf8e3563908fd204e273238c/lib/UnrarXLib/file.cpp#L178
https://github.com/xbmc/vfs.rar/blob/b66c6df9f1c4b683bf8e3563908fd204e273238c/lib/UnrarXLib/extract.cpp#L620
should use WideToChar, not WideToUtf. because WideToUtf only for apple system.

**Comment by taxigps** [comment]
@notspiff find the problem now, kodi crash in vfs.archive, not in vfs.rar. and like @Rechi say, it doesn't do what's expected. Applied #40 and it works.
