### ISSUE TITLE
Corrupt multipart rar-file leading to segfault

### ISSUE THREAD

**Issue by flindeberg** [xbmc/vfs.rar#44]
Could be connected to #43 and #39, but unsure. 

Corrupt and / or multipart rars with missing parts cause segfault (i.e. crashes Kodi hard). 

I do not consider failing a problem, but the segfault is indeed annoying. Got segfault on both Kodi 18.1 on Arch (Manjaro) and Kodi 18.2 on LibreElec, both running `RAR archive support 2.0.7` (on LibreElec via addons, on Manjaro via `kodi-addon-vfs-rar` in AUR). 

> // Cut from dmesg on Manjaro
> [46273.694902] JobWorker[10694]: segfault at 8 ip 00007fcedb313024 sp 00007fcee0e15be8 error 4 in vfs.rar.so.2.0.7[7fcedb2e2000+49000]
> 
> [47691.310114] JobWorker[11146]: segfault at 8 ip 00007f465c81a024 sp 00007f461efedbe8 error 4 in vfs.rar.so.2.0.7[7f465c7e9000+49000]
> 
> [48102.829368] JobWorker[12094]: segfault at 8 ip 00007f833b71b024 sp 00007f8311122be8 error 4 in vfs.rar.so.2.0.7[7f833b6ea000+49000]

The file in question is part of a multipart rar and unrar provides nothing more helpful than:

> $ unrar e "offending file"
> // cut for privacy
> Cannot find volume "next part of multipart rar"
> "file in multipart rar" - checksum error
> Total errors: 1

If it matters, the file(s) did not contain video data, but rather old backuped data from twenty years ago or so split into rar-archives for floppies (for some reason I had configured Kodi to scan a bit wider than just the movie directory on my server). Still, I do not think that faulty rar-files should cause segfault :smiley:

**Comment by pgarba** [comment]
Same problem here:

`JobWorker[1846]: segfault at 8 ip 00007f23858a8ef4 sp 00007f230e3bda48 error 4 in vfs.rar.so.2.0.7[7f2385876000+4b000]`

Any fix ?!

**Comment by hahahaplop** [comment]
same issue but for some reason kodi crashes at startup. I can provide a crash log.
`Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe91b15de54 in File::FileLength() () from /usr/lib/x86_64-linux-gnu/kodi/addons/vfs.rar/vfs.rar.so.2.0.7
`

**Comment by AlwinEsch** [comment]
The problem becomes fixed with https://github.com/xbmc/vfs.rar/pull/50

**Comment by AlwinEsch** [comment]
The new version is released:
- 3.3.0-Matrix
- 2.3.0-Leia

@hahahaplop @pgarba @flindeberg can you confirm the bug is fixed?

**Comment by hahahaplop** [comment]
The bug happened with a specific corrupted archive which I deleted since, not sure how to reproduce but will post here if it happens again

**Comment by AlwinEsch** [comment]
Was something comes again about this?

**Comment by AlwinEsch** [comment]
Without report it seems fixed.
