### ISSUE TITLE
Kodi hasn't yet branches Matrix so what are the master/matrix branches?

### ISSUE THREAD

**Issue by candrews** [xbmc/vfs.rar#52]
This repo has a matrix branch which seems to be ahead of the master branch.

Since Kodi hasn't branched matrix yet, according to https://github.com/xbmc/vfs.rar/blob/Leia/README.md the master branch of this repo should be used.

So what so the matrix branch and when should it be used?

**Comment by AlwinEsch** [comment]
The README.md here and on a lot of other addons need to improve for this cases.

For Kodi master branch, the Matrix branch on addon
For Kodi Leia branch, the Leia branch on addon.

The master branch is no more used currently on addons, only the for Kodi used Names.

**Comment by Rechi** [comment]
`git clone https://github.com/xbmc/vfs.rar.git` will check out the Leia branch not the master branch. 
Whatever other branches exist in this repo and how those are named is irrelevant.
