### ISSUE TITLE
RAR format - the video get interrupted randomly

### ISSUE THREAD

**Issue by Sopor** [xbmc/vfs.rar#73]
Something is really wrong with Kodi and vfs.rar. When playing ISO files (in RAR format) i can't jump forwards or backwards (chapters/titles) without the video get interrupted (the playback will stop).

When playing mkv files (in RAR format) it will suddenly jump forwards (several seconds) without any reason or i will get freezed frames. If i'm playing the same part of the video where it jumped forwards before it will now work, so it is nothing wrong with the files or mkv file.

If i unpack the mkv file or the ISO file i can jump whatever i want (i can jump forward and backward how fast i want) without any interrupt in the video.

It is the same thing in Windows as in my Vero.

**Comment by Sopor** [comment]
If i try to play an ISO (BluRAY 48GB) in RAR it takes about 2 minutes to get the `simplified menu` to show up. If i unpack the ISO it takes 6-7 seconds to open it. Again i get these random interrupts. After 4 minutes the playback stopped (RAR). If i play it again it will not stop at the same time and it can even play the whole video without any stops, so there is nothing wrong with the ISO (as i already have mentioned above). If i unpack and play it, there are no random interrupts when playing or jumping forwards/backwards and it takes less time to start it too (big ISO files as BluRay). Even if the `Vero 4K+` doesn't have the same power as my i9 CPU have, but 7 seconds unpacked and 2 minutes packed (STORED) is quite a big difference to open the `simplified menu`.

**Comment by babayaga40** [comment]
same issue im having! randomly failures during video play, it suddenly stops and goes back to menu. This has been recent, older verions of kodi did not have this issue (older versions of vfs).

**Comment by AlwinEsch** [comment]
Can you give a log about? Is this also with newest version or now better?
I'm think time delay problem is not fixed, but to make sure.

Seen by last fixes that there was a big hang in his thread which produced a big time during his RAR scans, this now fixed, but maybe not related to this here?

**Comment by Sopor** [comment]
I tested with the vfs.rar 2.3.0 and in ISO files it is still the same issue.

@AlwinEsch I sent you a log by email. Didn't you received it?

**Comment by AlwinEsch** [comment]
Log not arrived, you send to alwinus@kodi.tv?

**Comment by Sopor** [comment]
Yes, at Tue 2020-03-31 18:42

**Comment by babayaga40** [comment]
> Yes, at Tue 2020-03-31 18:42

please tell me if you figure this out, i have the exact same issue.

**Comment by babayaga40** [comment]
> Log not arrived, you send to [alwinus@kodi.tv](mailto:alwinus@kodi.tv)?

I have sent you a log as well to this email, right now 10/4-2020 :)

**Comment by Sopor** [comment]
When it skip frames the time suddenly show negative value (not everytime):
![image](https://user-images.githubusercontent.com/5789283/79150120-849c7a00-7dc8-11ea-926f-c1879d5e2f08.png)
I don't know if that can help you find the issue...

**Comment by AlwinEsch** [comment]
Maybe this becomes better on next version, there 3 fixes inside #81 
Not sure by bug from here, but maybe. I cross the finger.

For test here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/4/artifacts

**Comment by AlwinEsch** [comment]
The new version is released
@Sopor @babayaga40 can you confirm that problem from this issue is fixed?

**Comment by Sopor** [comment]
I wrote earlier that i get negative play time. It seems that i get that too when i listen to web radio. It is a simple pls file i run.

**Comment by Sopor** [comment]
I have watched a couple of episodes in Kodi 19 and vfs.rar 3.3.1 and it seems to work. I can jump forwards and backwards without any glitches and i didn't see any while it was playing either.

**Comment by Sopor** [comment]
Tested in Kodi 18.6 Git:20200509-66ae0f9f vfs.rar 2.3.1 and i can now play and jump as i want without the video stops playing.
