### ISSUE TITLE
Tv Scans Crash

### ISSUE THREAD

**Issue by bluboyo** [xbmc/vfs.rar#74]
Something has changed. I cant scan tv series for meta data. Kodi crashes. Cant see anything in the logs. Movies is fine. Only affects rar. I've tried different provinders and its the same. 

Anything i can do to help with this?

**Comment by DaVukovic** [comment]
> Anything i can do to help with this?

Yes. Provide the debulog. The fact that you don't see anything obvious doesn't mean the developer doesn't see anything as well ;)

**Comment by bluboyo** [comment]
[kodi.log](https://github.com/xbmc/vfs.rar/files/4423038/kodi.log)
Here you go. This one is better. Fiiiiiix it :P

**Comment by bluboyo** [comment]
I have noticed that if I scan one season at a time it works most of the time. Hole series work if there is one season. So allot of folders and files seems to make it crash.

**Comment by ketonic** [comment]
I am also having the same exact issue, on multiple computers and OS (Windows and Linux). I have tried to reinstall all of the software and removing all settings files. 

I have seen the issue about to long file paths, that might be the same issue i have.

BUT if i download 2.0.8 it works perfect so i bet you the issue have to do with RAR5 support.
EDIT: I spoke to soon i guess, it did crash as well, but added some files to the database (nothing showed up in the logs)
EDIT2: Moved back to 18.5 with 2.0.8 and so far so good, the scan has passed where it crashed the last time.

**Comment by ketonic** [comment]
So i have figured out what the issue was for me at least.
Some rar-files with .sub-files, removing them fixed the issue for me, adding them back makes it crash again. 

But i do have other rar-files with .sub-files and them work just fine.

**Comment by AlwinEsch** [comment]
Have currently not so much time, but I try to fix the next days.

**Comment by Paft** [comment]
2.0.8 with 18.5 on Windows seems to successfully scan my entire library but scanning the same library with the same versions on Android still crashes. I've mentioned this on the Kodi forums.

**Comment by AlwinEsch** [comment]
If this also on 2.0.8 it can really have to do with the `char temp[128];` here https://github.com/xbmc/vfs.rar/blob/Leia/src/RarFile.cpp#L52

Has tested with longer paths before, but has worked and has not seen until now this 128 byte.
Maybe some OS handle them different and not all produce a crash by them :thinking:?

Also can then a RAR work, where not in long folder, but with longer it crash without know why.

**Comment by AlwinEsch** [comment]
Found another massive problem where becomes fixed with them https://github.com/xbmc/vfs.rar/pull/75/commits/a2ab4ba7dc3f9106f9c2d54db11b712b218f23f7

Seen this now on RAR with music and content scan, there it has taken minutes until the Music Title image was shown and Kodi has freezen during his stop.

Think it really crashes here, but because of such problems I have to point out how errors should be described.

Had some times that crash was referred to, but was different.

| Type | Desc.
|----|-----------------------
| Crash | Kodi suddenly ends and is completely gone
| Frezze | Kodi runs and is displayed, but can no longer be used and controlled or e.g. a process is shown that never ends.
| Bug | Everything continues to run, only certain things cannot be carried out, e.g. sudden termination of playback, incorrect display, file opening not working.

**Comment by amazingdash** [comment]
> So i have figured out what the issue was for me at least.
> Some rar-files with .sub-files, removing them fixed the issue for me, adding them back makes it crash again.
> 
> But i do have other rar-files with .sub-files and them work just fine.

This looks like the problem I have in https://github.com/xbmc/vfs.rar/issues/68#issuecomment-607132302

@AlwinEsch does #77 contain a fix for this?

**Comment by AlwinEsch** [comment]
Hopefully yes, you can try the binary from here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-77/3/artifacts

**Comment by bluboyo** [comment]
[kodi.zip](https://github.com/xbmc/vfs.rar/files/4442709/kodi.zip)
Tried the new 2.3 version. Did a full scan and it crashed. Here is the log.

**Comment by bluboyo** [comment]
Tried a tvshow i know crasched before. this is from the log
2020-04-07 10:36:01.812 T:3296   ERROR: AddOnLog: RAR archive support: CRARControl::GetPassword: invalid data (no/invalid data file found at 'C:\Kodi18\portable_data\userdata\addon_data\vfs.rar\\rar-control.xml')

**Comment by AlwinEsch** [comment]
This `GetPassword` has nothing todo with the error and can be ignored (is wrongly shown as this has no passwords).

Can you look about the RAR package (last on your log). Is there a `.r44` or `.r45` present?
Maybe a bit heavy, but does WinRAR or other App works for full extract or bring it somewhere a error?

Could be wrong addon behave if something is missing or it has internal package errors.

**Comment by bluboyo** [comment]
Yes they are there. It goes all the way to 85. Checked the files and they are ok. No extraction iussues outside kodi. used winrar

**Comment by bluboyo** [comment]
I deleted all the meta data and rescaned all the movies. Now it works with the movies again. Do I dare do it with tv? Its a shitload of work scanning one season at a time...

**Comment by AlwinEsch** [comment]
The new version is released:
- 3.3.0-Matrix
- 2.3.0-Leia

@faltaren can you test with them to see it is fixed?

**Comment by bluboyo** [comment]
[kodi.log](https://github.com/xbmc/vfs.rar/files/4448232/kodi.log)
Crash :(. Here is the log.

**Comment by AlwinEsch** [comment]
There is on your log on `VideoPlayer::OpenFile` another addon (`plugin://`) and not a `rar://`, also is there no `AddOnLog: RAR archive support` or `CAddonSettings[vfs.rar]` inside where inform about `vfs.rar` use, are you sure that this come from addon?

Think there is more a bug inside the python addon.

**Comment by bluboyo** [comment]
Ok. How can we test this?

**Comment by AlwinEsch** [comment]
Think you taken the wrong log, on them which you brought first by https://github.com/xbmc/vfs.rar/issues/74#issuecomment-608037330 was it included (e.g. `AddOnLog: RAR archive support: CRARControl::VolumeChange`), but not on the last.

**Comment by bluboyo** [comment]
[kodi.log](https://github.com/xbmc/vfs.rar/files/4449226/kodi.log)
I dowloaded the installationfile again, did a clean install and only added the tv folder. Only the rar addon installed by me. Still crash. Here is the log.

**Comment by bluboyo** [comment]
[kodi.log](https://github.com/xbmc/vfs.rar/files/4449256/kodi.log)
One more with debug

**Comment by niklasholm** [comment]
@AlwinEsch Maybe rollback stable to 2.0.8 and tag everything newer as beta until these issues are resolved, because it's getting massively annoying having to downgrade all time.

**Comment by AlwinEsch** [comment]
I start now a big check by some TB about them.
And to compare there with new and old.

With the old I know also a lot of crashes, where it makes not direct sense for me.

**Comment by bluboyo** [comment]
[kodi.log](https://github.com/xbmc/vfs.rar/files/4450102/kodi.log)
Hey! I downgraded to 2.0.8 and I can do a full scan if I remove pippi langstrump. My rar movies with isofiles with in them dosent show up but everything else works. Here is the log with pippi. Kodi crasches when it scans. So all the folder problems came after 2.0.8. I also noticed that animal kingdom (one of the shows that crashed with the never versions), friends season 4 had double episodes even after a clean. Also ALL rarmovies is double after i scaned with 2.0.8 (even after clean). Should give you some clue. Crash on incomplete rars etc is still there.

**Comment by Paft** [comment]
I'm only using it on movies so far but 2.3.0 didn't crash once and "fully" scanned on Windows. Will test android at some point. Edit: I forgot to mention after installing 2.3.0 it started addinng duplicates so I had to start fresh. Just a FYI.

**Comment by bluboyo** [comment]
The problem arent with movies. Only Tv.

**Comment by RowanDDR** [comment]
> The problem arent with movies. Only Tv.

Might depend on your content? For me, the scan that normally takes 10 seconds when there is nothing new to detect, is now essentially hanging - after 5mins its still at 0% although log file shows scan IS happening, just very very very very slowly. When I disable VFS and rescan, its normal, 10 seconds. My scan uses UniversalMovieDatabase and TVDB to scan Movies and TV.

**Comment by bluboyo** [comment]
[kodi.log](https://github.com/xbmc/vfs.rar/files/4527933/kodi.log)
Still crash. Here is the log. Using 2.3.1

**Comment by AlwinEsch** [comment]
Thanks for the log.

This seems related to the bug inside Kodi itself, where is fixed with https://github.com/xbmc/xbmc/pull/17670.

But you must wait until Kodi Leia 18.7 is released. Without it comes to a deadloop and thats why crash.

**Comment by bluboyo** [comment]
Ok. Do you no any good pre release i can download?

**Comment by AlwinEsch** [comment]
You can take a nightly of Kodi Leia from here http://mirrors.kodi.tv/nightlies/windows/win64/Leia/ where have the fix inside.

If you try, can you look that the crash is gone, or maybe still something else present?

**Comment by bluboyo** [comment]
Did a full scan. No crash 😁. Even had some incomplete rara. No crash. Good job 😎
