### ISSUE TITLE
choppy / freeze frames / stutter on kodi 18.6+

### ISSUE THREAD

**Issue by Termin8or666** [xbmc/vfs.rar#76]
Ever since the kodi 18.6 upgrade on two vero 4k+ the rar addon playback has been choppy / freeze frames / stutter for 2-3 sec (version 2.2.2)
could happen 3 times during an episode but nothing is consistant.
Tried the Matrix build on the kodi 19 alpha, same result. version 3.2.0

The old archive (version 1.06 on kodi 18.6 and 1.2.0 on kodi 19) are ok but alot slower to "open" archives and start playback.

just me or is this a known problem ?

**Comment by amazingdash** [comment]
I also get random video freezes and glitches with v2.2.x. When I stop and reopen the video, they are gone. It's annoying because I can't reproduce it easily, it looks like I have to play the film a little bit before I see the glitch.
Kodi's log seems to have this kind of error when it happens: `ERROR: ffmpeg[7F9255551700]: [matroska,webm] Invalid length 0x3f7 > 0x8 for element with ID 0xE7 at 0x80606e0`.

**Comment by Sopor** [comment]
This seems to be the same as mine #73

**Comment by Sopor** [comment]
@Termin8or666 Have you tried to unpack the files and see if that will make it go away?

**Comment by Termin8or666** [comment]
If I use the older libarchive to play the rars everything is fine, its just after the kodi 18.6 upgrade that included the (version 2.2.2) the glitches occur.

**Comment by Termin8or666** [comment]
tested with 3.3.0 now, same issue.. the picture sometimes turn black during playback but that could be a kodi bug. when it stutters / freezes for a couple of sec ive found this in the log: 
ERROR: ffmpeg[0xaf73d660X]: [matroska,webm] Length 5 indicated by an EBML number's first byte 0x08 at pos 666115633 (0x27b41e31) exceeds max length 4.  

ERROR: ffmpeg[0xaf73d660X]: [matroska,webm] Element at 0x26032cc1 ending at 0x3362bf96 exceeds containing master element ending at 0x2603e1ff

**Comment by AlwinEsch** [comment]
Maybe this becomes better on next version, there 3 fixes inside #81 
Not sure by bug from here, but maybe. I cross the finger.

For test here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/4/artifacts

**Comment by Termin8or666** [comment]
did some testing on 3.3.1 and no problems yet :)

**Comment by Sopor** [comment]
I haven't seen any of these issues since i updated to Kodi 18.7.1 and 3.3.1 of vfs.rar.
