### ISSUE TITLE
Crashing on multi-rar files where file sizes are large

### ISSUE THREAD

**Issue by babayaga40** [xbmc/vfs.rar#78]
Reading from RAR archives where the RAR-files are about (or less or more) 500MB can cause kodi to crash back to the menu.

**Comment by phunkyfish** [comment]
If you report what you believe is a bug please always support a full debug log (and a crash log if possible).

**Comment by phunkyfish** [comment]
But if this is going back to the menu I doubt it's a crashing, a crash would kill kodi.

**Comment by babayaga40** [comment]
here a log where it only tries to open the rar-archive, but have to be unrarred to work, think it might be the same issue 

aaauhd.rar: RAR archive data, v2.0, os: Win32, flags: ArchiveVolume FirstVolume

https://pastebin.com/VJ3mSdwS

**Comment by AlwinEsch** [comment]
You have [vfs.libarchive](https://github.com/xbmc/vfs.libarchive) installed and no vfs.rar.

```
2020-04-07 19:21:35.796 T:7520  NOTICE: ADDON: vfs.libarchive v1.0.7 installed
```

As note if you install vfs.rar must be vfs.libarchive disabled.
