### ISSUE TITLE
Depend on UnrarXLib instead of bundling

### ISSUE THREAD

**Issue by candrews** [xbmc/vfs.rar#8]
Can you please depend on UnrarXLib instead of bundling it?

So the lib/UnrarXLib directory would be removed and CMakeLists.txt updated to depend on UnrarXLib.

Bundling libraries is generally not a good idea. For example, it makes managing security problems a lot more difficult, and one was just found in UnrarXLib - see https://bugs.chromium.org/p/project-zero/issues/detail?id=1286

**Comment by notspiff** [comment]
not at all possible. i have hacked it to pieces to work in kodi, and the changes are highly kodi specific. it's nothing upstream can or will carry.
