### ISSUE TITLE
Video won't play if in RAR format

### ISSUE THREAD

**Issue by Sopor** [xbmc/vfs.rar#80]
I have a video that will NOT play in `Kodi` or `VLC` (i can only see Kodi flash very very quick, but it won't crash or hang Kodi), but it will play perfect in `Media Player Classic Homecinema`. If i unpack it, it will play in all three players. The strange thing is that it works in `Media Player Classic Homecinema` as i already have mentioned.

I have seen the same thing in other RAR archive, so that is the reason i report it.

Debug log: https://paste.kodi.tv/owumoqonef.kodi

**Comment by AlwinEsch** [comment]
Should now work with 
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/2/artifacts (for tests) from https://github.com/xbmc/vfs.rar/pull/81, I bring it in later if no new bug comes with it  :smile:

**Comment by Sopor** [comment]
Yes, tested in both Kodi 18.6 and 19.0a and the video is working.

**Comment by AlwinEsch** [comment]
The new version with fix about is released
