### ISSUE TITLE
Video keeps stopping randomly with huge files on kodi 2.3.1

### ISSUE THREAD

**Issue by babayaga40** [xbmc/vfs.rar#83]
Video keeps stopping randomly with huge (usually on 4K ISO-files) files on Nvidia Sheild (android) with SMB. Log sent to developer earlier.

**Comment by AlwinEsch** [comment]
Do you use a `advancedsettings.xml` to define some extra parts on your Kodi?
Was it only by ISO files or also on normal videos?

Has played now much, much hours movies and TV shows, where worked on Linux and Windows and look later also on the Android versions.

**Comment by babayaga40** [comment]
> Do you use a `advancedsettings.xml` to define some extra parts on your Kodi?
> Was it only by ISO files or also on normal videos?
> 
> Has played now much, much hours movies and TV shows, where worked on Linux and Windows and look later also on the Android versions.

there has been no issues with x265 (pretty huge files 30+ GB, but muxed to .mkv), or TV-shows 1080/720, or 1080p. I only get this issue with 4K UHD Complete ISO-files at about 40++ GB).  Have not modified the .xml file

**Comment by babayaga40** [comment]
Do you have the log-file i sent?

**Comment by babayaga40** [comment]
It's not the same rar that gets affected, as the same UHD can last for an hour, and sometimes 5 mins, before it fails.

**Comment by babayaga40** [comment]
UPDATE: so it seems this issue also includes BluRay ISO files, have although not seen it on DVD isos. I ripped one of my BDs to BD50, did not have any use for them before. These are also at 30-40GB. So it seems it's only affecting ISO images.

**Comment by AlwinEsch** [comment]
Not seen a mail, if you send also yesterday by creation of issue, then is not arrived. Think you mean about **"Log sent to developer earlier."**

**Comment by babayaga40** [comment]
> Not seen a mail, if you send also yesterday by creation of issue, then is not arrived. Think you mean about **"Log sent to developer earlier."**

ah, yes, i sent to alwinus@kodi.tv 4/10/2020, 11:01 AM

sent it now,. one more time with the subject that refers to this issue/bug.

**Comment by AlwinEsch** [comment]
Maybe is now better, can someone try for Kodi Leia from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/2/artifacts

Found one RAR file where it stopped during seek, for this the second commit here https://github.com/xbmc/vfs.rar/pull/81 was added, hope thats for here is fixed.

**Comment by babayaga40** [comment]
> Maybe is now better, can someone try for Kodi Leia from here:
> https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/2/artifacts
> 
> Found one RAR file where it stopped during seek, for this the second commit here #81 was added, hope thats for here is fixed.

thanks! i will try it straight away :)

**Comment by babayaga40** [comment]
same problem, making a new logfile if that helps. i did use the 2.3.1 from the jenkins-kode compiles, this onecmake/addons/build/zips/vfs.rar+android-aarch64/vfs.rar-2.3.1.zip

**Comment by babayaga40** [comment]
new log has been sent

**Comment by AlwinEsch** [comment]
Still not arrived, how big is your log? And how is your mail start name? To identify if old maybe landed in spam.

**Comment by babayaga40** [comment]
> Still not arrived, how big is your log? And how is your mail start name? To identify if old maybe landed in spam.

log is 5MB could end up in spam, as many of my emails has done so lately

**Comment by babayaga40** [comment]
tried sending it from google now, i know many services has suddenly not being friendly to my host, for som reason.

**Comment by AlwinEsch** [comment]
Have checked about this bug and found that in some cases the unrar processing thread was not fast enough and Kodi read call has not becomed data. Normally should this no problem, but Kodi is there also a bit buggy and stopps playback :smirk:. 

It seems also related to the performance of the system, thats why it can work on faster ones, but on smaller it come.

Have added here a fix about https://github.com/xbmc/vfs.rar/pull/81 by **"fix RAR read support, if process thread delay to give data"**, for test here https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-81/4/artifacts. By them it try 3 times if not enough data was present, maybe I increase the attempts, if by few Android system fault still present

Think if nothing against to merge the request in next hours.

**Comment by AlwinEsch** [comment]
The new version with fix about is released.

@babayaga40 can you confirm the right work on your system?

**Comment by babayaga40** [comment]
> The new version with fix about is released.
> 
> @babayaga40 can you confirm the right work on your system?

Running a test now with BluRay ISO, will also run a UHD which is even bigger to complete the bug testing, thanks for all your hard work! I will report at both ISOs are tested and confirmed working :)

**Comment by babayaga40** [comment]
> The new version with fix about is released.
> 
> @babayaga40 can you confirm the right work on your system?

Good news! Tested on both BluRay ISO (about 40GB), no problem, also tested on huge 4K UHD ISO at 80GB, no issues there either :D couldn't be happier this is fixed :))

**Comment by AlwinEsch** [comment]
Juhu :smile:, thanks for test and report!
