### ISSUE TITLE
Kodi won't auto-load subtitles in RAR/RAR

### ISSUE THREAD

**Issue by Sopor** [xbmc/vfs.rar#84]
I'm now running 2.3.0 of vfs.rar and it is still not auto load if the rar file is STORED and the sub file inside was made with Compression method: BEST. This was a RAR4 archive running Kodi 18.6. It will work if i run it in  Kodi 17.6.

I wondering if this was a RAR5 issue? Maybe it was the STORED/BEST issue instead? I couldn't test it in Kodi 17.6 as we know that RAR5 is not supported in Kodi 17.6.

**Comment by Sopor** [comment]
I have now installed Kodi 19 and it won't auto-load external subtitles in RAR with vfs.rar 3.3.0 when the RAR file is compressed (not STORED).

**Comment by AlwinEsch** [comment]
Thanks for the Issue, I look about.

With **"RAR file is compressed"** brings me to idea about, maybe related with the prevent of video load (for screenshots) by compressed packages, as this to strong to extract GBytes of whole RAR for a screenshot and this then maybe also affect the subtitles.

On compressed is a direct read from RAR not possible and is added to Kodi's temporary dir.

By a stored (not compressed) it has worked as expected and was correct?

**Comment by Sopor** [comment]
In older Kodi/XBMC versions there was a limit how big the compressed RAR file could be. If the RAR file was bigger than X bytes it will show a dialog asking me if i want to unpack this large file. Most of the times you never saw this dialog on subtitles but if there was a lot of different languages the sub file could be quite big and that is also the reason they use BEST compression on that file. The compression ratio could be as high as 60%. If the RAR file was compressed but below this X limit it was extracted without any question dialog.

**Comment by Sopor** [comment]
Kodi 19.0 alpha1 (compiled 2020-04-17):
It seems that it doesn't matter if the RAR files are in STORED or BEST format. They won't auto-load. The archive was RAR4.

**Comment by AlwinEsch** [comment]
This part is now fixed within Leia and Matrix, after release of Kodi 18.8 is it then available for use.

- https://github.com/xbmc/xbmc/pull/18202
- https://github.com/xbmc/xbmc/pull/18201
